[package]
name = "chop-chop"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.1", package = "gtk4" }
adw = { version = "0.7.0", package = "libadwaita" }
relm4 = "0.9.1"
relm4-components = "0.9.1"

[build-dependencies]
glib-build-tools = "0.21.0"
